### PR TITLE
Fix isReachingTop for element scroll

### PR DESCRIPTION
**Pull request by tjadli**

### CODE REVIEW

**Comment by anasAsh** [comment]
Thanks for your merge request, would you please remove changes outside scroll.directive?

**Comment by tjadli** [comment]
it's done!

**Review by anasAsh — APPROVED** [review]

**Comment by anasAsh** [comment]
@tjadli do you have an NPM account, i want to add you to Collaborators list.

**Comment by tjadli** [comment]
@anassAsh Yeah of course, its the same tjadli.

**Comment by anasAsh** [comment]
added thanks, sorry I got caught up in work and life.

**Pull request merged**
